steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '--build-arg', 'USE_SECURE_PROTOCOL=true', '--build-arg', 'API_DOMAIN=${_API_DOMAIN}', '--build-arg', 'API_PORT=443', '--build-arg', 'WS_PORT=443', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/containers/frontend:$COMMIT_SHA', '.']
  dir: frontend
images:
- $LOCATION-docker.pkg.dev/$PROJECT_ID/containers/frontend:$COMMIT_SHA