apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
        - args:
            - sh
            - -c
            - ./docker-entrypoint.sh
          env:
            - name: API_PORT
              value: "3000"
            - name: APP_PORT
              value: "19006"
            - name: DATABASE_HOST
              value: db
            - name: MYSQL_DATABASE
              value: markdown_editor
            - name: MYSQL_DATABASE_USERNAME_FOR_APP
              value: markdown_editor_app
            - name: WS_PORT
              value: "3001"
          image: markdowneditor-api
          name: api
          ports:
            - containerPort: 3000
            - containerPort: 3001
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
status: {}
