version: "3.2"

services:
  frontend:
    build: ./frontend
    environment:
      DATABASE_HOST: db
      MYSQL_DATABASE: markdown_editor
      MYSQL_DATABASE_USERNAME_FOR_APP: markdown_editor_app
      MYSQL_DATABASE_PASSWORD_FOR_APP:
      API_PORT: 3000
      WS_PORT: 3001
      APP_PORT: 19006
    env_file:
      - ./frontend/.env
    ports:
      - target: 7007
        published: 7007
      - target: 19000
        published: 19000
      - target: 19002
        published: 19002
      - target: 19006
        published: 19006
    command: yarn start
  api:
    depends_on:
      - "db"
    build: ./api
    environment:
      DATABASE_HOST: db
      MYSQL_DATABASE: markdown_editor
      MYSQL_DATABASE_USERNAME_FOR_APP: markdown_editor_app
      MYSQL_DATABASE_PASSWORD_FOR_APP:
      API_PORT: 3000
      WS_PORT: 3001
      APP_PORT: 19006
    ports:
      - target: 3000
        published: 3000
      - target: 3001
        published: 3001
    command: sh -c ./docker-entrypoint.sh
  db:
    image: mysql:8.0.29
    environment:
      DATABASE_HOST: db
      MYSQL_DATABASE: markdown_editor
      MYSQL_DATABASE_USERNAME_FOR_APP: markdown_editor_app
      MYSQL_DATABASE_PASSWORD_FOR_APP:
      API_PORT: 3000
      WS_PORT: 3001
      APP_PORT: 19006
    env_file:
      - ./db/.env
    ports:
      - target: 3306
        published: 3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init/init-container.sh:/docker-entrypoint-initdb.d/1.sh
      - ./db/init/init-tables.sql:/docker-entrypoint-initdb.d/2.sql
      - ./db/init/init-user-procedures.sql:/docker-entrypoint-initdb.d/3.sql
      - ./db/init/init-document-procedures.sql:/docker-entrypoint-initdb.d/4.sql
volumes:
  db:
    driver: local
