x-common-variables: &common-variables
  MYSQL_DATABASE: markdown_editor
  MYSQL_DATABASE_USERNAME_FOR_APP: app
  MYSQL_DATABASE_PASSWORD_FOR_APP:

services:
  frontend:
    build: ./frontend
    ports:
      - 7007:7007
      - 19000:19000
      - 19002:19002
      - 19006:19006
    env_file:
      - ./frontend/.env
    command: yarn start
  api:
    depends_on:
      - "db"
    build: ./api
    environment:
      <<: *common-variables
      PORT: 19007
    ports:
      - 19007:19007
    command: sh -c ./docker-entrypoint.sh
  db:
    image: mysql:8.0.29
    env_file:
      - ./db/.env
    environment: *common-variables
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local
