x-db-port: &DB_PORT
  3306
x-api-port: &API_PORT
  3000
x-ws-port: &WS_PORT
  3001
x-storybook-ui-port: &STORYBOOK_UI_PORT
  7007
x-expo-go-app-port: &EXPO_GO_APP_PORT
  19000
x-expo-dev-tools-port: &EXPO_DEV_TOOLS_PORT
  19002
x-app-port: &APP_PORT
  19006
x-common-variables: &common-variables
  MYSQL_DATABASE: markdown_editor
  MYSQL_DATABASE_USERNAME_FOR_APP: markdown_editor_app
  MYSQL_DATABASE_PASSWORD_FOR_APP:
  API_PORT: *API_PORT
  WS_PORT: *WS_PORT
  APP_PORT: *APP_PORT

services:
  frontend:
    build: ./frontend
    environment: *common-variables
    env_file:
      - ./frontend/.env
    ports:
      - target: *STORYBOOK_UI_PORT
        published: *STORYBOOK_UI_PORT
      - target: *EXPO_GO_APP_PORT
        published: *EXPO_GO_APP_PORT
      - target: *EXPO_DEV_TOOLS_PORT
        published: *EXPO_DEV_TOOLS_PORT
      - target: *APP_PORT
        published: *APP_PORT
    command: yarn start
  api:
    depends_on:
      - "db"
    build: ./api
    environment:
      <<: *common-variables
    ports:
      - target: *API_PORT
        published: *API_PORT
      - target: *WS_PORT
        published: *WS_PORT
    command: sh -c ./docker-entrypoint.sh
  db:
    image: mysql:8.0.29
    environment: *common-variables
    env_file:
      - ./db/.env
    ports:
      - target: *DB_PORT
        published: *DB_PORT
    volumes:
      - db:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local
