#!/bin/bash

MYSQL_DATABASE=markdown_editor
MYSQL_DATABASE_USERNAME_FOR_APP=markdown_editor_app

mysql -u root -p$MYSQL_ROOT_PASSWORD << EOF
CREATE DATABASE $MYSQL_DATABASE;
DROP USER IF EXISTS '$MYSQL_DATABASE_USERNAME_FOR_APP'@'localhost';
CREATE USER '$MYSQL_DATABASE_USERNAME_FOR_APP'@'localhost' IDENTIFIED BY '$MYSQL_DATABASE_PASSWORD_FOR_APP';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE
ON $MYSQL_DATABASE.*
TO '$MYSQL_DATABASE_USERNAME_FOR_APP'@'localhost';
EOF

mysql -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE < ./init/init-tables.sql
mysql -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE < ./init/init-user-procedures.sql
mysql -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE < ./init/init-document-procedures.sql
