version: '3.1'

services:
  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_PASSWORD: password
    ports:
      - target: 3306
        published: 3306
    volumes:
      - ../db/init:/docker-entrypoint-initdb.d
