apiVersion: v1
data:
  API_PORT: "3000"
  WS_PORT: "3001"
  FRONTEND_DOMAIN: localhost
  FRONTEND_PORT: "4503" # Expecting Kubernetes port forwards frontend to this port
  DATABASE_HOST: db
  MYSQL_DATABASE: markdown_editor
  MYSQL_USER: markdown_editor_app
  REDIS_HOST: redis
  SENDER_EMAIL: markdown@kirakiraworx.com
  CONFIRMATION_EMAIL_SERVER_TYPE: SendGrid # Options: StandardMailServer | SendGrid | Gmail
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api-api-configmap
  name: api-configmap
