apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    io.kompose.service: db
  name: db-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
